// Code generated by "enumer -type=Color"; DO NOT EDIT.

package enum

import (
	"fmt"
)

const _ColorName = "UnspecifiedRedBlueGreen"

var _ColorIndex = [...]uint8{0, 11, 14, 18, 23}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_ColorIndex)-1) {
		return fmt.Sprintf("Color(%d)", i)
	}
	return _ColorName[_ColorIndex[i]:_ColorIndex[i+1]]
}

var _ColorValues = []Color{0, 1, 2, 3}

var _ColorNameToValueMap = map[string]Color{
	_ColorName[0:11]:  0,
	_ColorName[11:14]: 1,
	_ColorName[14:18]: 2,
	_ColorName[18:23]: 3,
}

// ColorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColorString(s string) (Color, error) {
	if val, ok := _ColorNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Color values", s)
}

// ColorValues returns all values of the enum
func ColorValues() []Color {
	return _ColorValues
}

// IsAColor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Color) IsAColor() bool {
	for _, v := range _ColorValues {
		if i == v {
			return true
		}
	}
	return false
}
