version: '3'

tasks:

  run:
    desc: "Run the node server for accessing the RPC client page"
    deps: [proto:generate]
    cmds:
      # Ugly, but didn't find a way to listen to rabbitmq to be UP (wait-for-it doesn't work)
      - sleep 11
      - npm run dev

  run:wait:
    desc: "Run the node server for accessing the RPC client page after 11sec"
    cmds:
      # Ugly, but didn't find a way to listen to rabbitmq to be UP (wait-for-it doesn't work)
      - sleep 11
      - task: run

  proto:lint:
    desc: "Run lint over proto files"
    cmds:
      - buf lint ../proto

  proto:generate:
    desc: "Generate proto files for frontend"
    aliases: [proto:gen]
    deps: [proto:lint]
    cmds:
      - npx buf generate --template ../buf.gen.ts.yaml ../proto
    sources:
      - ../proto/**/*.proto
    generates:
      - src/proto/gen/**/*.go