version: '3'

tasks:

  run:
    desc: "Run the node server for accessing the RPC client page"
    deps: [proto:generate]
    cmds:
      - npm run dev

  proto:lint:
    desc: "Run lint over proto files"
    cmds:
      - buf lint ../proto

  proto:generate:
    desc: "Generate proto files for frontend"
    aliases: [proto:gen]
    deps: [proto:lint]
    cmds:
      - npx buf generate --template ../buf.gen.ts.yaml ../proto
    sources:
      - ../proto/**/*.proto
    generates:
      - src/proto/gen/**/*.go