version: '3'

tasks:

  run:
    desc: "Run the RPC server"
    deps: [proto:generate]
    cmds:
      - go run cmd/rpcserver/main.go

  go:lint:
    desc: "Run lint over go files"
    preconditions:
      - gofumpt --version
    cmds:
      - gofumpt -l -w .

  proto:lint:
    desc: "Run lint over proto files"
    cmds:
      - buf lint ../proto

  proto:generate:
    desc: "Generate proto files for backend"
    aliases: [proto:gen]
    cmds:
      - buf generate --template ../buf.gen.go.yaml ../proto
    sources:
      - ../proto/**/*.proto
    generates:
      - api/proto/gen/**/*.go
