version: '3'

tasks:

  go:lint:
    desc: "Run lint over go files"
    cmds:
      - gofumpt -l -w .

  proto:lint:
    desc: "Run lint over proto files"
    cmds:
      - buf lint ../proto

  proto:generate:
    desc: "Generate proto files for backend"
    aliases: [proto:gen]
    deps: [proto:lint]
    cmds:
      - buf generate --template ../buf.gen.go.yaml ../proto
    sources:
      - ../proto/**/*.proto
    generates:
      - api/proto/gen/**/*.go
