version: '3'

tasks:

  run:
    desc: "Run the RPC server"
    deps: [proto:generate]
    cmds:
      # Ugly, but didn't find a way to listen to rabbitmq to be UP (wait-for-it doesn't work)
      - sleep 10
      - go run cmd/rpcserver_rabbitmq/main.go
      # The Watermill version doesn't work (the subscribe part)
      # - go run cmd/rpcserver_watermill/main.go

  go:lint:
    desc: "Run lint over go files"
    preconditions:
      - gofumpt --version
    cmds:
      - gofumpt -l -w .

  proto:lint:
    desc: "Run lint over proto files"
    cmds:
      - buf lint ../proto

  proto:generate:
    desc: "Generate proto files for backend"
    aliases: [proto:gen]
    cmds:
      - buf generate --template ../buf.gen.go.yaml ../proto
    sources:
      - ../proto/**/*.proto
    generates:
      - api/proto/gen/**/*.go
