version: '3'

services:
  devcontainer:
    build: .
    volumes:
      - ../..:/workspaces:cached
      # Link cache to speed-up the building process
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    command: sleep infinity